
export const members = [
    { name: "Ritik Jat", role: "Frontend Developer", image: "https://ui-avatars.com/api/?name=Ritik+Jat&background=0D8ABC&color=fff" },
    { name: "Vineet Suman", role: "Project Manager", image: "https://ui-avatars.com/api/?name=Vineet+Suman&background=F39C12&color=fff" },
    { name: "Vineet Kahar", role: "Technical Manager", image: "https://ui-avatars.com/api/?name=Vineet+Kahar&background=2ECC71&color=fff" },
    { name: "Rohan Yadav", role: "Backend Developer", image: "https://ui-avatars.com/api/?name=Rohan+Yadav&background=9B59B6&color=fff" },
    { name: "Manish Thakur", role: "Database Administrator", image: "https://ui-avatars.com/api/?name=Manish+Thakur&background=34495E&color=fff" },
    { name: "Abhishek Sen", role: "QA Engineer", image: "https://ui-avatars.com/api/?name=Abhishek+Sen&background=E74C3C&color=fff" },
    { name: "Abhishek Vishvakarma", role: "Security Analyst", image: "https://ui-avatars.com/api/?name=Abhishek+Vishvakarma&background=1ABC9C&color=fff" },
    { name: "Arpit Malviya", role: "DevOps Engineer", image: "https://ui-avatars.com/api/?name=Arpit+Malviya&background=27AE60&color=fff" },
    { name: "Dharmesh Malviya", role: "Cloud Engineer", image: "https://ui-avatars.com/api/?name=Dharmesh+Malviya&background=2980B9&color=fff" },
    { name: "Dhananjay Siloriya", role: "Frontend Analyst", image: "https://ui-avatars.com/api/?name=Dhananjay+Siloriya&background=8E44AD&color=fff" },
    { name: "Mayank Chouhan", role: "Mobile App Developer", image: "https://ui-avatars.com/api/?name=Mayank+Chouhan&background=8E44AD&color=fff" },
    { name: "Abhishek Patel", role: "Technical Writer", image: "https://ui-avatars.com/api/?name=Abhishek+Patel&background=D35400&color=fff" },
    { name: "Ankit Malviya", role: "Graphic Designer", image: "https://ui-avatars.com/api/?name=Ankit+Malviya&background=2C3E50&color=fff" },
    { name: "Ankit Prajapati", role: "Content Strategist", image: "https://ui-avatars.com/api/?name=Ankit+Prajapati&background=C0392B&color=fff" },
    { name: "Vijay Vishvakarma", role: "SEO Specialist", image: "https://ui-avatars.com/api/?name=Vijay+Vishvakarma&background=16A085&color=fff" },
    { name: "Niraj Mahajan", role: "Marketing Manager", image: "https://ui-avatars.com/api/?name=Niraj+Mahajan&background=F1C40F&color=fff" },
    { name: "Shivam Jat", role: "Support Engineer", image: "https://ui-avatars.com/api/?name=Shivam+Jat&background=E67E22&color=fff" },
    { name: "Virendra Dwivedi", role: "Analytics Lead", image: "https://ui-avatars.com/api/?name=Virendra+Dwivedi&background=BDC3C7&color=000" },
    { name: "Parth Panchal", role: "Frontend Architect", image: "https://ui-avatars.com/api/?name=Parth+Panchal&background=7F8C8D&color=fff" },
    { name: "Paritosh Sahu", role: "Backend Manager", image: "https://ui-avatars.com/api/?name=Paritosh+Sahu&background=27AE60&color=fff" },
    { name: "Nishant Agrawal", role: "UI/UX designer", image: "https://ui-avatars.com/api/?name=Nishant+Agrawal&background=9B59B6&color=fff" },
    { name: "Vikas Gadariya", role: "Cloud Analyst", image: "https://ui-avatars.com/api/?name=Vikas+Gadariya&background=34495E&color=fff" },
];

